layout_spectrum: 0.4936395
typography_spectrum: 0.7731822
color:
  saturation: 0.3860204
  lightness: 0.299275
  brandStrength: 0.9498208
  brandColors:
    - '#0A0F12'
    - '#C8D9F3'
    - '#523C31'
    - '#A37E63'
    - '#5C8FBA'
  rhythmicContrast: 0.8177485
name: Jean-Nicholas
