collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6075269
  brandStrength: 0.9498208
  lightness: 0.3727598
  brandColors:
    - '#F5F6F8'
    - '#141519'
    - '#314C5F'
    - '#C0BEBF'
    - '#27A8BA'
  rhythmicContrast: 0.4283154
typography_spectrum: 0.9318997
layout_spectrum: 0.2007169
name: Jean-Nicholas
